pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Deploy to Dev') {
            when {
            expression { env.BRANCH_NAME == 'dev' }

            }
            steps {
                sh '''
                cd ansible
                ansible-playbook -i inventory-dev deploy.yml
                '''
            }
        }

        stage('Deploy to Prod') {
            when {
                 expression { env.BRANCH_NAME == 'main' }

            }
            steps {
                sh '''
                cd ansible
                ansible-playbook -i inventory-prod deploy.yml
                '''
            }
        }
    }

stage('Debug Branch') {
    steps {
        echo "BRANCH_NAME = ${env.BRANCH_NAME}"
    }
}

    post {
        success {
            echo "Deployment successful"
        }
        failure {
            echo "Deployment failed"
        }
    }
}

